### GET users
GET http://localhost:3000/users

### POST users
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "j@d.com",
  "password": "12Az!3456"
}

### GET a user
GET http://localhost:3000/users/1

### PATCH a user
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "Jane Doe"
}

### DELETE a user
DELETE http://localhost:3000/users/1