services:
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data: {}
